// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gprgjahjduyisxperemy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdwcmdqYWhqZHV5aXN4cGVyZW15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzI5MzIsImV4cCI6MjA2NDkwODkzMn0.Fy-5ZBb4gfgSfqMy6mUCAoY20PHEikgbTELwRYknYd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);